### ISSUE TITLE
Generating the world

### ISSUE THREAD

**Issue by Kaczuc** [BentoBoxWorld/CaveBlock#28]
Is it possible to check the default generator for CaveBlock modes to only generate the worlds from additionals instead of the default ones?

**Comment by BONNe** [comment]
In bukkit.yml you need to specify that caveblock worlds uses BentoBox generator:

```
worlds:
  caveblock-world:
    generator: BentoBox
  caveblock-world_nether:
    generator: BentoBox
  caveblock-world_the_end:
    generator: BentoBox
```
And in server.properties you need to set caveblock-world as starting level:
```
level-name=caveblock-world
```
